### PR TITLE
Modifications to incorporate axolotl

### PR DESCRIPTION
**Pull request by kwailo888**
Hopefully this will be a good primer to complete the integration of axolotl into the C# branch. There are errors i'm sure but it's quite close i hope .. regards Brian

### CODE REVIEW

**Comment by mgp25** [comment]
@kwailo888 can you post here also an output (debug log): logging, uploading keys and sending message?

**Comment by kwailo888** [comment]
Sure .. basically from what i can see sending the prekeys to WA is getting a 406:

rx <iq from="s.whatsapp.net" type="error" id="1453283299-22">
rx   <error code="406" text="not-acceptable"></error>
rx </iq>

. i'm able to get the users SessionCipher keys and the GetCipherKeysFromUser with no issues and they pass the curve25519 key test.

When I try to decrypt the message the session looks to get the signed prekey on failure sends a retry node which returns a 400:

tx  <receipt id="0B4A0784998E0EE9C50" to="60125222790@s.whatsapp.net" type="retry" t="1451710823">
tx    <retry v="1" count="1" id="0B4A0784998E0EE9C50" t="1451710823"></retry>
tx    <registration>g-ge</registration>
tx  </receipt>

rx <ack from="60125222790@s.whatsapp.net" class="receipt" type="retry" id="0B4A0784998E0EE9C50" error="400"></ack>

tx  <receipt id="8F999FF3CA8E8651C3B" to="628388985428@s.whatsapp.net" type="retry" t="1451710823">
tx    <retry v="1" count="1" id="0B4A0784998E0EE9C50" t="1453266813"></retry>
tx    <registration>g-x$</registration>
tx  </receipt>

rx <ack from="60125222790@s.whatsapp.net" class="receipt" type="retry" id="0B4A0784998E0EE9C50" error="400"></ack>

hope that's useful

**Comment by mgp25** [comment]
@kwailo888 the issue could be in the format you are sending the values or maybe the values are bad calculated.

Have you compared the results from Chat API?

**Comment by kwailo888** [comment]
Sorry for the late reply we're in different time zones :) .. haven't tried debugging the php application to compare. I"m setting up my php debug environment now and will see how they compare. I've a feeling it's caused  by the initial rejection of the keys by WA as per the 406 error. this makes sense that the second retry request would return an error not being able to locate my signed prekey on the WA server. Will let you know the outcome later today.

**Comment by KduOliva** [comment]
Is this actually working?

**Comment by florisrobbemont** [comment]
I'm currently working on trying to get this to work. I have succesfully (based on @kwailo888 's other repo) implemented decryption of messages, but I'm having some issues with sending encrypted messages. The WhatsApp server will accept plain text, but it sends a retry once I use Axolotl to encrypt it. I'm not sure how to fix this since I'm not getting any relevant information from WhatsApp

**Comment by KduOliva** [comment]
Hi Floris!,

I think this API is the only serious API around, but it seems all these processes (registration, send, receive, etc) seem very unstable. Its too much people complaints about blocks, failures, etc.
I even  had tons blocked numbers only testing my apps.
It looks like we're always fighting the whatsapp

I wonder how the tools available on the market can ensure send spans, and work properly...


On 25 de fev de 2016, at 7:40 AM, Floris Robbemont <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm currently working on trying to get this to work. I have succesfully (based on @kwailo888<https://github.com/kwailo888> 's other repo) implemented decryption of messages, but I'm having some issues with sending encrypted messages. The WhatsApp server will accept plain text, but it sends a retry once I use Axolotl to encrypt it. I'm not sure how to fix this since I'm not getting any relevant information from WhatsApp

**Comment by eaba** [comment]
@florisrobbemont  can you upload your version for testing?

**Comment by florisrobbemont** [comment]
My code is basically a large rewrite of the original API. I've compared it to the PHP API and it seems to working correctly now (instead for encrypting messages, decrypting is working fine).

Also, I have not been blocked since I added a durable storage for the prekeys. Once you don't send new prekeys every time you startup the application WhatsApp will not block you.

Can we chat somewhere to discuss this? I can upload the code but I only implemented a RavenDB Axolotl storage... It can work if you install RavenDB, but it won't work out of box.

**Comment by KduOliva** [comment]
Sure, my Skype is kdu.oliva.


On 25 de fev de 2016, at 9:52 AM, Floris Robbemont <notifications@github.com<mailto:notifications@github.com>> wrote:


My code is basically a large rewrite of the original API. I've compared it to the PHP API and it seems to working correctly now (instead for encrypting messages, decrypting is working fine).

Also, I have not been blocked since I added a durable storage for the prekeys. Once you don't send new prekeys every time you startup the application WhatsApp will not block you.

Can we chat somewhere to discuss this? I can upload the code but I only implemented a RavenDB Axolotl storage... It can work if you install RavenDB, but it won't work out of box.

**Pull request merged**
